In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect("../data/ecommerce_sales.db")

In [3]:
df = pd.read_csv("../data/ecommerce_sales_analytics_5000.csv")

In [4]:
df["order_date"] = pd.to_datetime(df["order_date"])

In [5]:
df.to_sql(
    "ecommerce_sales",
    conn,
    if_exists="replace",
    index=False
)

5000

In [6]:
query = """
SELECT
    COUNT(*) AS total_orders,
    SUM(revenue) AS total_revenue,
    AVG(revenue) AS average_order_revenue
FROM ecommerce_sales;
"""

result = pd.read_sql_query(query, conn)

result

   total_orders  total_revenue  average_order_revenue
0          5000     5109775.74            1021.955148

In [7]:
query = """
SELECT
    product_category,
    COUNT(*) AS orders,
    SUM(quantity) AS total_quantity,
    ROUND(SUM(revenue), 2) AS total_revenue,
    ROUND(AVG(revenue), 2) AS average_order_revenue
FROM ecommerce_sales
GROUP BY product_category
ORDER BY total_revenue DESC;
"""

category_sql = pd.read_sql_query(query, conn)

category_sql

,product_category,orders,total_quantity,total_revenue,average_order_revenue
0,Electronics,1777,7109,1829899.22,1029.77
1,Clothing,1531,6171,1531931.72,1000.61
2,Home,969,3949,982083.92,1013.50
3,Beauty,723,2995,765860.88,1059.28

In [8]:
query = """
SELECT
    region,
    COUNT(*) AS orders,
    ROUND(SUM(revenue), 2) AS total_revenue,
    ROUND(AVG(revenue), 2) AS average_order_revenue
FROM ecommerce_sales
GROUP BY region
ORDER BY total_revenue DESC;
"""

region_sql = pd.read_sql_query(query, conn)

region_sql

  region  orders  total_revenue  average_order_revenue
0   West    1289     1345582.16                1043.90
1  North    1276     1281508.45                1004.32
2  South    1208     1246640.90                1031.99
3   East    1227     1236044.23                1007.37

In [9]:
query = """
SELECT
    customer_id,
    COUNT(*) AS orders,
    ROUND(SUM(revenue), 2) AS total_revenue,
    ROUND(AVG(revenue), 2) AS average_order_value
FROM ecommerce_sales
GROUP BY customer_id
ORDER BY total_revenue DESC
LIMIT 10;
"""

top_customers_sql = pd.read_sql_query(query, conn)

top_customers_sql

   customer_id  orders  total_revenue  average_order_value
0         1663      14       17680.69              1262.91
1         1955      10       16265.15              1626.51
2         1675      11       15036.46              1366.95
3         1276      11       15023.71              1365.79
4         1647      11       14894.97              1354.09
5         1804      10       14330.98              1433.10
6         1193       7       14151.65              2021.66
7         1836       9       14110.78              1567.86
8         1957      12       13956.95              1163.08
9         1735       8       13146.25              1643.28

In [10]:
query = """
SELECT
    strftime('%Y-%m', order_date) AS month,
    COUNT(*) AS orders,
    ROUND(SUM(revenue), 2) AS total_revenue
FROM ecommerce_sales
GROUP BY month
ORDER BY month;
"""

monthly_sql = pd.read_sql_query(query, conn)

monthly_sql.head()

     month  orders  total_revenue
0  2022-01      31       35624.89
1  2022-02      28       29908.89
2  2022-03      31       30309.28
3  2022-04      30       30781.96
4  2022-05      31       41629.24

In [11]:
monthly_sql.tail()

       month  orders  total_revenue
160  2035-05      31       33393.87
161  2035-06      30       25205.26
162  2035-07      31       23944.48
163  2035-08      31       29354.74
164  2035-09       9        4952.23